# NumPy

## The Scientific Python Trilogy

Why is Python so popular for research work?

MATLAB has typically been the most popular "language of technical computing", with strong built-in support for efficient numerical analysis with matrices (the *mat* in MATLAB is for Matrix, not Maths), and plotting.

Other dynamic languages have cleaner, more logical syntax (Ruby, Scheme)

But Python users developed three critical libraries, matching the power of MATLAB for scientific work:

* Matplotlib, the plotting library created by [John D. Hunter](https://en.wikipedia.org/wiki/John_D._Hunter)
* NumPy, a fast matrix maths library created by [Travis Oliphant](http://continuum.io/our-team/index)
* IPython, the precursor of the notebook, created by [Fernando Perez](http://fperez.org)

By combining a plotting library, a matrix maths library, and an easy-to-use interface allowing live plotting commands
in a persistent environment, the powerful capabilities of MATLAB were matched by a free and open toolchain.

We've learned about Matplotlib and IPython in this course already. NumPy is the last part of the trilogy.

## Limitations of Python Lists

The normal Python List is just one dimensional. To make a matrix, we have to nest Python arrays:

In [5]:
x= [range(5) for something_unused in range(5)]

In [6]:
x

[[0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4]]

Applying an operation to every element is a pain:

In [7]:
x+5

TypeError: can only concatenate list (not "int") to list

In [8]:
[[elem +5 for elem in row] for row in x]

[[5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9]]

Common useful operations like transposing a matrix or reshaping a 10 by 10 matrix into a 20 by 5 matrix are not easy to code in raw Python lists.

## The NumPy array

NumPy's array type represents a multidimensional matrix $M_{i,j,k...n}$

The NumPy array seems at first to be just like a list:

In [9]:
import numpy as np
my_array=np.array(range(5))

In [10]:
my_array

array([0, 1, 2, 3, 4])

In [11]:
my_array[2]

2

In [12]:
for element in my_array:
    print "Hello" * element


Hello
HelloHello
HelloHelloHello
HelloHelloHelloHello


We can also see our first weakness of NumPy arrays versus Python lists:

In [13]:
my_array.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

For NumPy arrays, you typically don't change the data size once you've defined your array,
whereas for Python lists, you can do this efficiently. However, you get back lots of goodies in return...

## Elementwise Operations

But most operations can be applied element-wise automatically!

In [ ]:
my_array * 2

These "vectorized" operations are very fast:

In [ ]:
big_list=range(10000)
big_array=np.arange(10000)

In [ ]:
%%timeit
[x**2 for x in big_list]

In [ ]:
%%timeit
big_array**2

## Arange and linspace

NumPy has two easy methods for defining floating-point evenly spaced arrays:

In [ ]:
x=np.arange(0,10,0.1)
x

We can quickly define non-integer ranges of numbers for graph plotting:

In [ ]:
import math

In [ ]:
values=np.linspace(0, math.pi, 100) # Start, stop, number of steps

In [ ]:
values

NumPy comes with 'vectorised' versions of common functions which work element-by-element when applied to arrays:

In [ ]:
%matplotlib inline
from matplotlib import pyplot as plt
plt.plot(values, np.sin(values))

So we don't have to use awkward list comprehensions when using these.

## Multi-Dimensional Arrays

NumPy's true power comes from multi-dimensional arrays:

In [ ]:
np.zeros([3,4,2])

Unlike a list-of-lists in Python, we can reshape arrays:

In [ ]:
x=np.array(range(40))
y=x.reshape([4,5,2])
y

And index multiple columns at once:

In [ ]:
y[3,2,1]

Including selecting on inner axes while taking all from the outermost:

In [ ]:
y[:,2,1]

And subselecting ranges:

In [ ]:
y[2:,:1,:]

And transpose arrays:

In [ ]:
y.transpose()

You can get the dimensions of an array with `shape`

In [ ]:
y.shape

In [14]:
y.transpose().shape

NameError: name 'y' is not defined

Some numpy functions apply by default to the whole array, but can be chosen to act only on certain axes:

In [15]:
x=np.arange(12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
x.sum(1) # Sum along the second axis, leaving the first.

array([ 3, 12, 21, 30])

In [17]:
x.sum(0) # Sum along the first axis, leaving the second.

array([18, 22, 26])

In [18]:
x.sum() # Sum all axes

66

## Array Datatypes

A Python `list` can contain data of mixed type:

In [19]:
x=['hello', 2, 3.4]

In [20]:
type(x[2])

float

In [21]:
type(x[1])

int

A NumPy array always contains just one datatype:

In [22]:
np.array(x)

array(['hello', '2', '3.4'], 
      dtype='|S5')

NumPy will choose the least-generic-possible datatype that can contain the data:

In [23]:
y=np.array([2, 3.4])

In [24]:
y

array([ 2. ,  3.4])

In [25]:
type(y[0])

numpy.float64

## Broadcasting

This is another really powerful feature of NumPy

By default, array operations are element-by-element:

In [26]:
np.arange(5)*np.arange(5)

array([ 0,  1,  4,  9, 16])

If we multiply arrays with non-matching shapes we get an error:

In [27]:
np.arange(5) * np.arange(6)

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [28]:
np.zeros([2,3])*np.zeros([2,4])

ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

In [29]:
m1 = np.arange(100).reshape([10, 10])

In [30]:
m2 = np.arange(100).reshape([10, 5, 2])

In [31]:
m1+m2

ValueError: operands could not be broadcast together with shapes (10,10) (10,5,2) 

Arrays must match in all dimensions in order to be compatible:

In [32]:
np.ones([3,3])*np.ones([3,3]) # Note elementwise multiply, *not* matrix multiply.

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

**Except**, that if one array has any Dimension 1, then the data is **REPEATED** to match the other.

In [33]:
m1=np.arange(10).reshape([10,1])
m1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [34]:
m2=m1.transpose()
m2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
m1.shape # "Column Vector"

(10, 1)

In [36]:
m2.shape # "Row Vector"

(1, 10)

In [37]:
m1+m2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [38]:
10*m1+m2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

This works for arrays with more than one unit dimension. 

## Newaxis

Broadcasting is very powerful, and numpy allows indexing with `np.newaxis` to temporarily create new one-long dimensions on the fly.

In [39]:
x=np.arange(10).reshape(2,5)
y=np.arange(8).reshape(2,2,2)

In [40]:
x.reshape(2,5,1,1)

array([[[[0]],

        [[1]],

        [[2]],

        [[3]],

        [[4]]],


       [[[5]],

        [[6]],

        [[7]],

        [[8]],

        [[9]]]])

In [48]:
x[:,:,np.newaxis,np.newaxis].shape

(2, 5, 1, 1)

In [49]:
y[:,np.newaxis,:,:].shape

(2, 1, 2, 2)

In [41]:
res=x[:,:,np.newaxis,np.newaxis]*y[:,np.newaxis,:,:]

In [42]:
res.shape

(2, 5, 2, 2)

In [43]:
np.sum(res)

830

Note that `newaxis` works because a $3 \times 1 \times 3$ array and a $3 \times 3$ array contain the same data,
differently shaped:

In [44]:
threebythree=np.arange(9).reshape(3,3)
threebythree

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
threebythree[:,np.newaxis,:]

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

## Dot Products

NumPy multiply is element-by-element, not a dot-product:

In [ ]:
np.arange(9).reshape(3,3) * np.arange(3,12).reshape(3,3)

To get a dot-product, do this:

In [ ]:
np.dot(np.arange(9).reshape(3,3), np.arange(3,12).reshape(3,3))

In [ ]:
x = np.ones([3,5])
y = np.ones([5,4])

In [ ]:
(x[:,:,np.newaxis]*y[np.newaxis,:,:]).sum(1)

## Array DTypes

Arrays have a "dtype" which specifies their datatype:

In [ ]:
x=[2, 3.4, 7.2, 0]

In [ ]:
np.array(x)

In [ ]:
np.array(x).dtype

These are, when you get to know them, fairly obvious string codes for datatypes: 
    NumPy supports all kinds of datatypes beyond the python basics.

NumPy will convert python type names to dtypes:

In [ ]:
int_array= np.array(x, dtype=int)

In [ ]:
float_array=np.array(x, dtype=float)

In [ ]:
int_array

In [ ]:
float_array

In [ ]:
int_array.dtype

In [ ]:
float_array.dtype

## Record Arrays

These are a special array structure designed to match the CSV "Record and Field" model. It's a very different structure
from the normal numPy array, and different fields *can* contain different datatypes. We saw this when we looked at CSV files:

In [ ]:
x=np.arange(50).reshape([10,5])

In [ ]:
record_x=x.view(dtype={'names': ["col1", "col2", "another", "more", "last"], 
                       'formats': [int]*5 } )

In [ ]:
record_x

Record arrays can be addressed with field names like they were a dictionary:

In [ ]:
record_x['col1']

We've seen these already when we used NumPy's CSV parser.

## Logical arrays, masking, and selection

Numpy defines operators like == and < to apply to arrays *element by element*

In [ ]:
x=np.zeros([3,4])
x

In [ ]:
y=np.arange(-1,2)[:,np.newaxis]*np.arange(-2,2)[np.newaxis,:]
y

In [ ]:
iszero =  x==y
iszero

A logical array can be used to select elements from an array:

In [ ]:
y[np.logical_not(iszero)]

Although when printed, this comes out as a flat list, if assigned to, the *selected elements of the array are changed!*

In [ ]:
y[iszero]=5

In [ ]:
y

## Numpy memory

Numpy memory management can be tricksy:

In [ ]:
x=np.arange(5)
y=x[:]

In [ ]:
y[2]=0
x

In [ ]:
x=np.arange(5)
x=x+2
x

We must use `np.copy` to force separate memory. Otherwise NumPy tries it's hardest to make slices be *views* on data.

Now, this has all been very theoretical, but let's go through a practical example, and see how powerful NumPy can be.